function plotRDTs(varargin)
% It plots 3rd and 4th order RDT fluctuations along s for RING 
%% Inputs
% Mandatory argument
% RDT : structure generated by computeRDTfluctuation
%
%% Usage examples
% plotRDT(RDT);

%% History
% SJ  2024/08/21 

RDT = getargs(varargin,[]);
Spos  = RDT.buildup_fluctuation.s;
buildup_fluctuation =RDT.buildup_fluctuation;


%% plotting 3rd order RDTs
figure()
plot(Spos, abs(buildup_fluctuation.h21000), '-g','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h30000), '-b','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h10110), '-r','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h10020), '-k','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h10200), '-c','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h20001), '-m','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h00201), 'Color','#7E2F8E','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h10002), 'Color','#EDB120','LineWidth',2);
xlabel('S[m]');ylabel('Amplitude of RDTs');
grid on;set(gca,'Fontsize',14)
title('3rd order RDTs ');
legend('h21000', 'h30000', 'h10110', 'h10020',...
       'h10200', 'h20001', 'h00201', 'h10002','NumColumns', 3,'Location','northwest');
%% plotting 4th order RDTs
figure()
plot(Spos, abs(buildup_fluctuation.h22000), '-g','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h11110), '-b','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h00220), '-r','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h31000), '-k','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h40000), '-c','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h20110), '-m','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h11200), 'Color','#7E2F8E','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h20020), 'Color','#EDB120','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h20200), 'Color','#A2142F','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h00310), 'Color','#D95319','LineWidth',2);
hold on;
plot(Spos, abs(buildup_fluctuation.h00400), '-y','LineWidth',2);
xlabel('S[m]');ylabel('Amplitude of RDTs');
grid on;set(gca,'Fontsize',14)
title('4th order RDTs ');
legend('h22000', 'h11110', 'h00220', 'h31000', 'h40000',...
       'h20110', 'h11200', 'h20020', 'h20200', 'h00310', 'h00400','NumColumns', 3,'Location','northwest');
