function [NewLAT,penalty] = fitfullTune(LAT, fam1, fam2, lb, ub, tunes)
%fits full tune (with integer part)
%
Variab1 = atVariableBuilder(LAT,{fam1,fam2},...
          {{'PolynomB', {1,2}},{'PolynomB', {1,2}}},lb,ub);
%Constr1  = atlinconstraint(length(LAT)+1,{{'mu',{1}}},tunes(1),tunes(1),1);
%Constr2  = atlinconstraint(length(LAT)+1,{{'mu',{2}}},tunes(2),tunes(2),1);

%Const1=struct('Fun',@(RING,~,~)getfulltune(RING),...
%               'Min',tunes(1),...
%               'Max',tunes(1),...
%               'RefPoints',[],...
%               'Weight',1);  
Constr1 = struct('Fun',@(LAT,ld,~)mux(ld),...
                     'Min',tunes(1),...
                     'Max',tunes(1),...
                     'RefPoints',1:length(LAT)+1,...
                     'Weight',1);
Constr2 = struct('Fun',@(LAT,ld,~)muy(ld),...
                     'Min',tunes(2),...
                     'Max',tunes(2),...
                     'RefPoints',1:length(LAT)+1,...
                     'Weight',1);
Constraints = [Constr1 Constr2];

[NewLAT,penalty,dmin] = atmatch(LAT,Variab1,Constraints,1E-6,1000,0,@fminsearch); %fmincon
             
end



