function plotDAdist(varargin)
% plots distribution of DAs 
%% Inputs
% Mandatory argument
% DAdist : structure generated by calcDAdist
% 
% Optional arguments
% XmaxDA : horizontal limits for DA plots are (-XmaxDA,XmaxDA) [m]
% YmaxDA : vertical limits for DA plots are (0,YmaxDA) [m]
% If not givenm, the two value aboce are taken from
%       DAdist.outputs.DAoptions
%
% Optional flags
% verbose : prints out diagnbostics 
%% Usage examples
% plotDAdist(DAdist);
% plotDAdist(DAdist_std,'XmaxDA', 0.012, 'YmaxDA', 0.004);
%
% see also calcDAdist

%% History
% 2024/03/29
%
%% Input argument parsing
%
DAdist   = getargs(varargin,[]);
verbosef = any(strcmpi(varargin,'verbose'));
XmaxDA   = getoption(varargin,'XmaxDA',DAdist.outputs.DAoptions.XmaxDA);
YmaxDA   = getoption(varargin,'YmaxDA',DAdist.outputs.DAoptions.YmaxDA);

nseeds = DAdist.inputs.nseeds;
DAmode = DAdist.outputs.DAoptions.DAmode;
DAVs   = DAdist.outputs.DAVs;

if (strcmpi(DAmode,'border'))
   figure; xlabel('X [mm]'); ylabel('Y [mm]');grid;
   xlim([-XmaxDA XmaxDA]*1000);ylim([0 YmaxDA]*1000);hold;
else
    fprintf('%s DA dist plot requires border DA calc mode. DA mode is %s . Aborting...\n',...
             datetime, DAmode);
    return
end

for i=1:nseeds+1
 if (verbosef)
     fprintf('Iteration n. %4d \n', i-1);
 end
     
 if (strcmpi(DAmode,'border'))
     if (i>1)  
        plot(DAVs(:,2*i-1)*1000,DAVs(:,2*i)*1000,'-ob');
     else
        plot(DAVs(:,2*i-1)*1000,DAVs(:,2*i)*1000,'-ok');
     end
 end
end
 


