function plotDA(varargin)
% plots the Dynamic aperture
%   
%% Inputs
% Mandatory argument
% DAS : structure generated by calcDA
% 
% Optional arguments
% XmaxDA : horizontal limits for DA plots are (-XmaxDA,XmaxDA) [m]
% YmaxDA : vertical limits for DA plots are (0,YmaxDA) [m]
% If not given, the two values above are taken from
%       DAdist.outputs.DAoptions
%
% Optional flags
% verbose : prints out diagnostics 
%% Usage examples
% plotDA(DA);
% plotDA(DA,'XmaxDA', 0.012, 'YmaxDA', 0.004);

%% History
% PFT 2024/05/01
% PFT 2024/05/05 bug fix for grid mode plotting

%% Input argument parsing
%
DAS      = getargs(varargin,[]);
verbosef = any(strcmpi(varargin,'verbose'));
XmaxDA   = getoption(varargin,'XmaxDA',DAS.outputs.DAoptions.XmaxDA);
YmaxDA   = getoption(varargin,'YmaxDA',DAS.outputs.DAoptions.YmaxDA);

DAmode = DAS.outputs.DAoptions.DAmode;
DAV    = DAS.outputs.DAV;
npdax  = DAS.outputs.DAoptions.npdax;
npday  = DAS.outputs.DAoptions.npday;

switch DAmode
     case 'border'
         figure;plot(DAV(:,1)*1000,DAV(:,2)*1000,'-ob');
         xlabel('X [mm]'); ylabel('Y [mm]');grid;
         xlim([-XmaxDA XmaxDA]*1000);ylim([0 YmaxDA]*1000);

     case 'grid'
         DAM = zeros(npday+1,2*npdax+1);
         k= 1;
         for i=0:npday
            for j= 1:2*npdax+1
              DAM(npday+1-i,j)=DAV(k);
              k=k+1;
             end
          end
          DAM=DAM*255;
          map=[0 0.75 0; 1 1 1];
          figure;image([-XmaxDA*1000,XmaxDA*1000],[YmaxDA*1000,0],DAM);
          ax=gca;
          ax.YDir='normal';
          colormap(map);
          xlabel('X[mm]');
          ylabel('Y[mm]');    
          xlim([-XmaxDA XmaxDA]*1000);ylim([0 YmaxDA]*1000);grid;  
 end
