function plotADTS(adts,varargin)
% Plots amplitude dependetn tune shifts
%% Mandatory inputs  
% adts: structure generated by the calcADTS function
%
%% Optional inputs
%
% note: defaults are taken from adts structure
%
% plotmode: 'abs' : plots full tune value (including integer part)
%           'rel' : plots tune variations with respect to small amplitude
%                   tunes.
% plane: 'X', 'Y', 'XY', 'td' (td draws a tune diagram - fractional part only)
% resorder: resonance order for tune diagram, default = 5
% qxrange=[qxmin qymin]: horizontal plot range in tune diagram,  default =[0 1]
% qyrange=[qymin qymax]: vertical plot range in tune diagram, default= [0 1]
%
%% Usage examples
% plotADTS(adts,'plane','x','plotmode','rel');
% plotADTS(adts,'plane','td','qxrange',[0.2 0.3],'resorder',3);

%% Input argument parsing
plotmode = getoption(varargin,'plotmode',adts.inputs.plotmode);
plane    = getoption(varargin,'plane',adts.inputs.plane);
resorder = getoption(varargin,'resorder',5);
qxrange  = getoption(varargin,'qxrange',[0.0 1.0]);
qyrange  = getoption(varargin,'qyrange',[0.0 1.0]);

xmin  = adts.inputs.xmin;
xmax  = adts.inputs.xmax;
ymax  = adts.inputs.ymax;
amplx = adts.outputs.amplx;
amply = adts.outputs.amply;

%% Plots ADTS
switch plotmode
    case 'abs'
       Qxxplot  = adts.outputs.Qxx;
       Qyxplot  = adts.outputs.Qyx;
       Qxyplot  = adts.outputs.Qxy;
       Qyyplot  = adts.outputs.Qyy;

    case 'rel'
        Qxxplot  = adts.outputs.dQxx;
        Qyxplot  = adts.outputs.dQyx;
        Qxyplot  = adts.outputs.dQxy;
        Qyyplot  = adts.outputs.dQyy;

    otherwise
        fprintf('%s Error in plotADTS. Unknown plot mode : %s \n', ...
                   datetime, plotmode);
        return
end

switch plane

    case {'x';'X'}
        if not(isempty(amplx))
            figure; xlim([xmin*1000,xmax*1000]);
            plot(amplx*1000,Qxxplot,'-ok');xlabel('X[mm]');
            hold on;
            if (strcmpi(plotmode,'abs'))
                ylabel('Qx');
                yyaxis right; 
            else
                ylabel('dQ');
            end
            plot(amplx*1000,Qyxplot,'-or');
            if (strcmpi(plotmode,'abs'))
                ylabel('Qy');
                legend({'Qx';'Qy'});
            else
                legend({'dQx';'dQy'});
            end
            grid on;
        end
        
    case {'y';'Y'}
        if not(isempty(amply))
            figure; xlim([0,ymax*1000]); 
            plot(amply*1000,Qxyplot,'-ok');xlabel('Y[mm]');
            hold on;
            if (strcmpi(plotmode,'abs'))
                ylabel('Qx');
                yyaxis right; 
            else
                ylabel('dQ');
            end
            plot(amply*1000,Qyyplot,'-or');
            if (strcmpi(plotmode,'abs'))
                ylabel('Qy');
                legend({'Qx';'Qy'});
            else
                legend({'dQx';'dQy'});
            end
            grid on;
        end

    case {'xy';'XY';'xY';'Xy'}
        if not(isempty(amplx))
            figure; xlim([xmin*1000,xmax*1000]);
            plot(amplx*1000,Qxxplot,'-ok');xlabel('X[mm]');
            hold on;
            if (strcmpi(plotmode,'abs'))
                ylabel('Qx');
                yyaxis right; 
            else
                ylabel('dQ');
            end
            plot(amplx*1000,Qyxplot,'-or');
            if (strcmpi(plotmode,'abs'))
                ylabel('Qy');
                legend({'Qx';'Qy'});
            else
                legend({'dQx';'dQy'});
            end
            grid on;
        end

        if not(isempty(amply))
            figure; xlim([0,ymax*1000]); 
            plot(amply*1000,Qxyplot,'-ok');xlabel('Y[mm]');
            hold on;
            if (strcmpi(plotmode,'abs'))
                ylabel('Qx');
                yyaxis right; 
            else
                ylabel('dQ');
            end
            plot(amply*1000,Qyyplot,'-or');
            if (strcmpi(plotmode,'abs'))
                ylabel('Qy');
                legend({'Qx';'Qy'});
            else
                legend({'dQx';'dQy'});
            end
            grid on;
        end

    case {'td'}
        Qxxfrac=adts.outputs.Qxxfrac;
        Qyxfrac=adts.outputs.Qyxfrac;
        Qxyfrac=adts.outputs.Qxyfrac;
        Qyyfrac=adts.outputs.Qyyfrac;

        figure;plot(Qxxfrac,Qyxfrac,'ok');hold;
        plot(Qxyfrac,Qyyfrac,'or');
        plot_net(resorder,qxrange(1),qxrange(2),...
                          qyrange(1),qyrange(2));
                          
        xlabel('qx');ylabel('qy');
        grid;
        title(strcat('Res order = ',num2str(resorder)));

    otherwise
        fprintf('%s Error in plotADTS: unknown plane: %s \n',datetime,plane);       
        return
end
    
