function plotTLTdist(varargin)
% plots distribution of Touschek LIfetimes 
%% Inputs
% Mandatory argument
% TLdist : structure generated by calcTLTdist
% 
% Optional flags
% plotorbrms: plots the rms of the uncorrected and corrected orbits for all
%             seeds
% dpmaxplot : maximum of energy deviation axis, default =  LMA.deltalimit
% dpminplot : minimum of energy deviation axis, default = -LMA.deltalimit
%
%% Usage examples
% plotTLTdist(TLdist);
% plotTLTdist(TLdist,'plotorbrms');
% plotLMAdist(TLdist,'plotorbrms','verbose',1);
%
% see also calcTLTdist

%% History
% PFT 2024/07/05, first version

%% Input argument parsing
%
TLdist       = getargs(varargin,[]);
plotorbrmsf  = any(strcmpi(varargin,'plotorbrms'));
verboselevel = getoption(varargin,'verbose',0);

%% Plots Touschek lifetime 

figure; plot(TLdist.outputs.TLs/3600, '-o')
xlabel('Seed');ylabel('Touschek LIfetime [hr]');
grid on

if (plotorbrmsf)
   figure; 
   plot(TLdist.outputs.LMAdist.outputs.orb0_stds(1,2:end)*1000,'-o');
   xlabel('seed #');
   ylabel('x/y[mm]');
   hold;
   plot(TLdist.outputs.LMAdist.outputs.orb0_stds(3,2:end)*1000,'-o');
   legend({'X','Y'});
   title('rms orbit before correction');

   figure; 
   plot(TLdist.outputs.LMAdist.outputs.orb_stds(1,2:end)*1000,'-o');
   xlabel('seed #');
   ylabel('x/y[mm]');
   hold;
   plot(TLdist.outputs.LMAdist.outputs.orb_stds(3,2:end)*1000,'-o');
   legend({'X','Y'});
   title('rms orbit after correction');
end



 


