function plotLMAdist(varargin)
% plots distribution of LMSs 
%% Inputs
% Mandatory argument
% LMAdist : structure generated by calcLMAdist
% 
% Optional flags
% plotorbrms: plots the rms of the uncorrected and corrected orbits for all
%             seeds
%% Usage examples
% plotLMAdist(LMAdist);
% plotLMAdist(LMAdist,'plotorbrms');
% plotLMAdist(LMAdist,'plotorbrms','verbose',1);
%
% see also calcLMAdist

%% History
% PFT 2024/06/16

%% Input argument parsing
%
LMAdist      = getargs(varargin,[]);
plotorbrmsf  = any(strcmpi(varargin,'plotorbrms'));
verboselevel = getoption(varargin,'verbose',0);

%% Preamble
Spos      = LMAdist.outputs.Spos;
map_l_av  = LMAdist.outputs.map_l_av;
map_h_av  = LMAdist.outputs.map_h_av;
map_l_std = LMAdist.outputs.map_l_std;
map_h_std = LMAdist.outputs.map_h_std;

%% Plots LMA distribution

figure;errorbar(Spos, map_l_av*100,map_l_std*100,'-o');
hold;errorbar(Spos,map_h_av*100,map_h_std*100 ,'o-');
xlabel('S[m]');
ylabel('Local Momentum Aperture [%]');
grid on;
ylim([-15,15]);

if (plotorbrmsf)
   figure; 
   plot(LMAdist.outputs.orb0_stds(1,2:end)*1000,'-o');
   xlabel('seed #');
   ylabel('x/y[mm]');
   hold;
   plot(LMAdist.outputs.orb0_stds(3,2:end)*1000,'-o');
   legend({'X','Y'});
   title('rms orbit before correction');

   figure; 
   plot(LMAdist.outputs.orb_stds(1,2:end)*1000,'-o');
   xlabel('seed #');
   ylabel('x/y[mm]');
   hold;
   plot(LMAdist.outputs.orb_stds(3,2:end)*1000,'-o');
   legend({'X','Y'});
   title('rms orbit after correction');
end



 


