function phandles=plotOrbdist(varargin)
% plots distribution of closed orbits 
%% Inputs
% Mandatory argument
% ERlat : structure generated by the "generate_errlatt" function
% 
% Optional arguments
%
% plottitle : adds title to plot
% verbose   : defines level of verbose output, default=0, i.e. no output
%
%% Outputs
%  phandles : cell array with handles to generated plots
%
%% Usage examples
% plotOrbdist(ERlat);
% plotOrbdist(ERlat,'plottitle','Test');
%
% see also generate_errlatt

%% History
% PFT 2024/07/26 : PFT, first version

%% Input argument parsing
%
ERlat      = getargs(varargin,[]);

verbosef  = getoption(varargin,'verbose',0);
plottitle = getoption(varargin,'plottitle','');


%% Plots Closed Orbit distribution

figure; 
plot(ERlat.outputs.orb0_stds(1,2:end)*1000,'-o');
xlabel('seed #');
ylabel('x/y[mm]');
hold on;
plot(ERlat.outputs.orb0_stds(3,2:end)*1000,'-o');
legend({'X','Y'});
title(strcat(plottitle,{' :rms orbit before correction'}));
phandles{1}=gcf;
figure; 
plot(ERlat.outputs.orb_stds(1,2:end)*1E6,'-o');
xlabel('seed #');
ylabel('x/y[µm]');
hold on;
plot(ERlat.outputs.orb_stds(3,2:end)*1E6,'-o');
legend({'X','Y'});
title(strcat(plottitle,{' :rms orbit after correction'}));
phandles{2}=gcf;




 


