function plotLattice(LS)
% Plots lattice functions and performance parameters
% This function taes as input a structure generated bythe cLatt function
% Many plots are availeble, typical
% is to comment out plots
% 
%% Inputs
% Mandatory arguments
% LS: structre generated by the cLatt function.

%% Basic Plots - twiss parameters
atplot(LS.ACHROMAT);

%% Design orbit deviation 
plotDO(LS,'dev');
%}
%% Field and Gradient
%plotfield(LS.LattData.FG);

%% Dynamic Aperture without errors on and off-energy
plotDA(LS.LattPerf.DA.xy_0);
plotDA(LS.LattPerf.DA.xy_p3);
plotDA(LS.LattPerf.DA.xy_m3);

%% Dynamic Aperture without errors in (x,dp) and (y,dp) planes
plotDA(LS.LattPerf.DA.xydp);

%% Dynamic aperture with errors on( x,y) plane
plotDAdist(LS.LattPerf.DAdist.xy,'plotorbrms');

%% Dynamic aperture with errors on( x,dp) and (y,p) planes
plotDAdist(LS.LattPerf.DAdist.xydp);

%% Tune maps
plotTuneMap(LS.LattPerf.TM.xy,'plotmode','rel');
plotTuneMap(LS.LattPerf.TM.difxy,'caxrange',[-10 -2],'rate');
plotTuneMap(LS.LattPerf.TM.difxdp,'caxrange',[-10 -2],'rate');
plotTuneMap(LS.LattPerf.TM.difydp,'caxrange',[-10 -2],'rate');

qxmin=LS.LattPerf.atsummary.tunes(1)+0.8*min(LS.LattPerf.TM.difxy.outputs.dQxgridxy);
qxmax=LS.LattPerf.atsummary.tunes(1)+3.0*max(LS.LattPerf.TM.difxy.outputs.dQxgridxy);
qymin=LS.LattPerf.atsummary.tunes(2)+0.8*min(LS.LattPerf.TM.difxy.outputs.dQygridxy);
qymax=LS.LattPerf.atsummary.tunes(2)+3.0*max(LS.LattPerf.TM.difxy.outputs.dQygridxy);
plotTuneMap(LS.LattPerf.TM.difxy,'plottype','fmxy','qxrange',[qxmin qxmax],'qyrange',[qymin qymax]);


qxmin=LS.LattPerf.atsummary.tunes(1)+1.0*min(LS.LattPerf.TM.difxdp.outputs.dQxgridxdp);
qxmax=LS.LattPerf.atsummary.tunes(1)+1.0*max(LS.LattPerf.TM.difxdp.outputs.dQxgridxdp);
qymin=LS.LattPerf.atsummary.tunes(2)+1.0*min(LS.LattPerf.TM.difxdp.outputs.dQygridxdp);
qymax=LS.LattPerf.atsummary.tunes(2)+1.0*max(LS.LattPerf.TM.difxdp.outputs.dQygridxdp);
plotTuneMap(LS.LattPerf.TM.difxdp,'plottype','fmxdp','qxrange',[qxmin qxmax],'qyrange',[qymin qymax]);

qxmin=LS.LattPerf.atsummary.tunes(1)+2.0*min(LS.LattPerf.TM.difydp.outputs.dQxgridydp);
qxmax=LS.LattPerf.atsummary.tunes(1)+0.2*max(LS.LattPerf.TM.difydp.outputs.dQxgridydp);
qymin=LS.LattPerf.atsummary.tunes(2)+0.5*min(LS.LattPerf.TM.difydp.outputs.dQygridydp);
qymax=LS.LattPerf.atsummary.tunes(2)+2.0*max(LS.LattPerf.TM.difydp.outputs.dQygridydp);
plotTuneMap(LS.LattPerf.TM.difydp,'plottype','fmydp','qxrange',[qxmin qxmax],'qyrange',[qymin qymax]);


%% Local Momentum Aperture without errors 
plotLMA(LS.LattPerf.LMA);
plotLMA(LS.LattPerf.TL.outputs.LMA); % use this if LMA data comes from
                                       Touschek lifetime calculation 

%% Local Momentum aperture with errors
plotLMAdist(LS.LattPerf.LMAdist);
plotLMAdist(LS.LattPerf.TLdist.outputs.LMAdist); % use this if LMA data comes from
                                                   Touschek lifetime calculation 

%}



