function printLog(LS)
% prints the log files of a lattice structure created by the cLatt function
%% Inputs
% Mandatory arguments
% LS: structure generated by the cLatt function.
%
fprintf('%s Log from Lattice:  %s \n', datetime, LS.Lattice_Name);
if (isfield(LS,'Log'))
    nlog = numel(LS.Log);
    for i=1:nlog
        fprintf('%s \n', char(LS.Log{i}));
    end

end